Client: WebAudioPlayer - Create and Destroy WebAudioPlayer
rdkcentral/rialto pull request #267
Opened 2024-02-07 10:57 UTC by skyshaha1

Summary: Test the WebAudioPlayer APIs in the client component tests.
Type: Feature
Test Plan: Unittests, Component Tests.
Jira: RIALTO-415

2024-02-07 11:40 UTC, skywilliamsonl commented on tests/common/matchers/WebAudioPlayerProtoRequestMatchers.h
> +// #include "MediaCommon.h"
Remove

2024-02-07 11:40 UTC, skywilliamsonl commented on tests/common/matchers/WebAudioPlayerProtoRequestMatchers.h
> +MATCHER_P3(createWebAudioPlayerRequestMatcher, audioMimeType, priority, config, "")
Check config values

2024-02-07 11:40 UTC, skywilliamsonl commented on tests/componenttests/client/CMakeLists.txt
> +        tests/mse/CreateWebAudioPlayerTest.cpp
Not mse, create a new folder

2024-02-07 11:40 UTC, skywilliamsonl commented on tests/componenttests/client/tests/base/WebAudioPlayerTestMethods.cpp
> +// const int32_t kValue{1};
Remove

2024-02-07 11:40 UTC, skywilliamsonl commented on tests/componenttests/client/tests/base/WebAudioPlayerTestMethods.cpp
> +std::shared_ptr<WebAudioConfig> m_config = std::make_shared<WebAudioConfig>();
member variables should be in the WebAudioPlayerTestMethods

2024-02-07 11:40 UTC, skywilliamsonl commented on tests/componenttests/client/tests/mse/CreateWebAudioPlayerTest.cpp
> + *   Expect that create session api is called on the server
create web audio instead of create session

2024-02-07 11:40 UTC, skywilliamsonl commented on tests/componenttests/client/tests/mse/CreateWebAudioPlayerTest.cpp
> + *   Check that web audio player has been added.
Should be web audio client and you don't do this step. Id remove this for now and do in your next PR.

2024-02-07 13:44 UTC, skyproudmanp requested changes

2024-02-07 13:44 UTC, skyproudmanp commented on tests/common/matchers/WebAudioPlayerProtoRequestMatchers.h
> +    return (kRequest->web_audio_player_handle());
Should there be an == check in this MATCHER ?

2024-02-07 13:44 UTC, skyproudmanp commented on tests/componenttests/client/tests/base/WebAudioPlayerTestMethods.h
> +using ::testing::WithArgs;
Probably one to discuss with Luke, but should we have "using" statements which aren't used within the source file (I think StrictMock is the only one used here)

2024-02-07 14:35 UTC, skyproudmanp approved these changes

2024-02-08 15:53 UTC, skywilliamsonl approved these changes

2024-02-09 07:49 UTC, skywilliamsonl commented on tests/unittests/media/client/ipc/webAudioPlayerIpc/CreateTest.cpp
> -    return ((kRequest->audio_mime_type() == audioMimeType) && (kRequest->priority() == priority));
Use the matcher in common/matchers/WebAudioPlayerProtoRequests.h. Can deliver this and make the change in your next PR.

2024-02-09 09:51 UTC, merged